export interface ProviderInstructions {
  provider: string;
  apexSupported: boolean;
  cnameSteps: string[];
  aRecordSteps?: string[];
  nsSteps?: string[];
  gotcha?: string;
}

const INSTRUCTIONS: Record<string, ProviderInstructions> = {
  Cloudflare: {
    provider: "Cloudflare",
    apexSupported: true,
    cnameSteps: [
      "Log in to dash.cloudflare.com and select your domain",
      'Click DNS in the left sidebar → Records',
      'Click Add record',
      'Type: CNAME | Name: your subdomain (e.g. events) | Target: sites.woco-net.com',
      'Proxy status: DNS Only (grey cloud) ← this must be grey, not orange',
      'Click Save',
    ],
    aRecordSteps: [
      "Log in to dash.cloudflare.com and select your domain",
      'Click DNS in the left sidebar → Records',
      'Look for an existing A record with Name: @ — if it exists, click its Edit icon',
      'If no A record exists, click Add record',
      'Type: A | Name: @ | IPv4: 46.225.174.72',
      'Proxy status: DNS Only (grey cloud) ← this must be grey, not orange',
      'Click Save',
    ],
    gotcha: "Proxy status must be DNS Only (grey cloud). If it shows an orange cloud, click it to toggle to grey — otherwise traffic never reaches your site.",
  },
  GoDaddy: {
    provider: "GoDaddy",
    apexSupported: true,
    cnameSteps: [
      "Sign in → Domain Portfolio → click your domain",
      "Click DNS",
      "Click Add New Record → Type: CNAME",
      "Name: your subdomain (e.g. www or events) — not the full domain",
      "Value: sites.woco-net.com",
      "Click Save",
    ],
    aRecordSteps: [
      "Sign in → Domain Portfolio → click your domain",
      "Click DNS",
      "Find the existing A record for @ and click the edit icon",
      "Change the value to 46.225.174.72",
      "Click Save — or click Add New Record → Type: A | Name: @ | Value: 46.225.174.72",
    ],
    gotcha: "Domain Protection requires active 2-step verification before DNS changes are allowed.",
  },
  Namecheap: {
    provider: "Namecheap",
    apexSupported: true,
    cnameSteps: [
      "Log in → Domain List → Manage next to your domain",
      "Click Advanced DNS tab",
      "Click Add New Record → Type: CNAME Record",
      "Host: subdomain prefix only (e.g. www) — Namecheap appends the domain automatically",
      "Value: sites.woco-net.com",
      "Click the green checkmark to save",
    ],
    aRecordSteps: [
      "Log in → Domain List → Manage next to your domain",
      "Click Advanced DNS tab",
      "Find any existing A record for @ — click the edit icon to modify it, or Add New Record",
      "Type: A Record | Host: @ | Value: 46.225.174.72",
      "Click the green checkmark to save",
    ],
    gotcha: "DNS records are only editable when using Namecheap BasicDNS, PremiumDNS, or FreeDNS.",
  },
  Squarespace: {
    provider: "Squarespace Domains",
    apexSupported: true,
    cnameSteps: [
      "Go to account.squarespace.com/domains → click your domain",
      "Click DNS Settings → scroll to Custom Records → click Add record",
      "Re-authenticate when prompted",
      "Type: CNAME | Name: www | Target: sites.woco-net.com",
      "Click Save",
    ],
    aRecordSteps: [
      "Go to account.squarespace.com/domains → click your domain",
      "Click DNS Settings → scroll to Custom Records → click Add record",
      "Re-authenticate when prompted",
      "Type: A | Name: @ | Value: 46.225.174.72",
      "Click Save",
    ],
    gotcha: "Squarespace may require you to delete the default A record before adding a custom one.",
  },
  IONOS: {
    provider: "IONOS",
    apexSupported: true,
    cnameSteps: [
      "Log in → Domains & SSL",
      "Click the gear/Actions icon next to your domain → Manage Subdomains",
      "Click the gear icon next to the subdomain → DNS",
      "Click ADD RECORD → select CNAME",
      "Hostname: subdomain (e.g. www) | Point to: sites.woco-net.com",
      "Click Save",
    ],
    aRecordSteps: [
      "Log in → Domains & SSL",
      "Click your domain → DNS",
      "Find the A record for @ or the root domain — click the edit icon",
      "Set the value to 46.225.174.72",
      "Click Save",
    ],
    gotcha: "Adding a CNAME to a subdomain removes all IONOS-managed services for that subdomain (email forwarding, FTP). This is expected.",
  },
  "AWS Route 53": {
    provider: "AWS Route 53",
    apexSupported: true,
    cnameSteps: [
      "AWS Console → Route 53 → Hosted zones → click your domain's zone",
      "Click Create record",
      "Record name: subdomain (e.g. www) | Record type: CNAME",
      "Value: sites.woco-net.com",
      "TTL: 300 (default) → click Create records",
    ],
    aRecordSteps: [
      "AWS Console → Route 53 → Hosted zones → click your domain's zone",
      "Click Create record",
      "Record name: leave blank (apex/root) | Record type: A",
      "Value: 46.225.174.72",
      "TTL: 300 → click Create records",
    ],
    gotcha: "Do not edit the NS record set inside Route 53 — change NS at the domain registrar instead.",
  },
  "Name.com": {
    provider: "Name.com",
    apexSupported: true,
    cnameSteps: [
      "Log in → My Domains → click your domain",
      "Click Manage DNS Records",
      "Type: CNAME | Host: subdomain (e.g. www) | Answer: sites.woco-net.com",
      "TTL: 300 → click Add Record",
    ],
    aRecordSteps: [
      "Log in → My Domains → click your domain",
      "Click Manage DNS Records",
      "Type: A | Host: @ | Answer: 46.225.174.72",
      "TTL: 300 → click Add Record",
    ],
  },
  Hover: {
    provider: "Hover",
    apexSupported: true,
    cnameSteps: [
      "Log in at hover.com → click your domain name",
      "Click the DNS tab → Add a record",
      "Type: CNAME | Hostname: subdomain (e.g. www) | Target Name: sites.woco-net.com",
      "Click Add Record",
    ],
    aRecordSteps: [
      "Log in at hover.com → click your domain name",
      "Click the DNS tab → Add a record",
      "Type: A | Hostname: @ | IP Address: 46.225.174.72",
      "Click Add Record",
    ],
  },
  Porkbun: {
    provider: "Porkbun",
    apexSupported: true,
    cnameSteps: [
      "Log in → Domain Management → Details next to your domain",
      "Click the DNS/edit icon → Add Record",
      "Type: CNAME | Host: subdomain (e.g. www) | Answer: sites.woco-net.com",
      "Click Add",
    ],
    aRecordSteps: [
      "Log in → Domain Management → Details next to your domain",
      "Click the DNS/edit icon → Add Record",
      "Type: A | Host: leave blank (for root) | Answer: 46.225.174.72",
      "Click Add",
    ],
    gotcha: "Porkbun blocks adding a CNAME if an A or AAAA record already exists for the same subdomain — delete the conflicting record first.",
  },
  OVHcloud: {
    provider: "OVHcloud",
    apexSupported: true,
    cnameSteps: [
      "Log in to OVH Control Panel → Web Cloud → Domain names → your domain",
      "Click the DNS zone tab → Add an entry → select CNAME",
      "Subdomain: your subdomain (e.g. www)",
      "Target: sites.woco-net.com. ← trailing dot is required",
      "Click Next → Confirm",
    ],
    aRecordSteps: [
      "Log in to OVH Control Panel → Web Cloud → Domain names → your domain",
      "Click the DNS zone tab → Add an entry → select A",
      "Subdomain: leave blank (for root/apex)",
      "Target: 46.225.174.72",
      "Click Next → Confirm",
    ],
    gotcha: "The trailing dot is mandatory on CNAME targets in OVH. Without it, the target is treated as a subdomain of your own zone.",
  },
  Gandi: {
    provider: "Gandi",
    apexSupported: true,
    cnameSteps: [
      "Log in to admin.gandi.net → Domain → your domain",
      "Click DNS records tab → Add",
      "Type: CNAME | Name: subdomain (e.g. www) | Hostname: sites.woco-net.com",
      "Click Create",
    ],
    aRecordSteps: [
      "Log in to admin.gandi.net → Domain → your domain",
      "Click DNS records tab → Add",
      "Type: A | Name: @ | IPv4 address: 46.225.174.72",
      "Click Create",
    ],
    gotcha: "Switching to external NS disables Gandi's LiveDNS editor. Set up records at Cloudflare before switching.",
  },
  "123-reg": {
    provider: "123-reg",
    apexSupported: true,
    cnameSteps: [
      "Log in to 123-reg Control Panel → Domain Portfolio",
      "Select your domain → click DNS in the toolbar",
      "Add New Record → Type: CNAME",
      "Hostname: subdomain (e.g. www) | Value: sites.woco-net.com | TTL: 3600",
      "Click Save",
    ],
    aRecordSteps: [
      "Log in to 123-reg Control Panel → Domain Portfolio",
      "Select your domain → click DNS in the toolbar",
      "Add New Record → Type: A",
      "Hostname: @ | Value: 46.225.174.72 | TTL: 3600",
      "Click Save",
    ],
    gotcha: "123-reg is owned by GoDaddy Group. Some accounts may show a GoDaddy-style interface.",
  },
  "One.com": {
    provider: "One.com",
    apexSupported: true,
    cnameSteps: [
      "Log in to One.com Control Panel → Advanced settings → DNS settings",
      "Click DNS records tab → under Create new record, click CNAME",
      "Hostname: subdomain (e.g. www) | Domain name (alias of): sites.woco-net.com",
      "Click Create record",
    ],
    aRecordSteps: [
      "Log in to One.com Control Panel → Advanced settings → DNS settings",
      "Click DNS records tab → under Create new record, click A",
      "Hostname: @ (or leave blank) | IP address: 46.225.174.72",
      "Click Create record",
    ],
  },
  Strato: {
    provider: "Strato",
    apexSupported: true,
    cnameSteps: [
      "Log in at strato.de → Domains → Domain management",
      "Click the cogwheel next to your domain → DNS tab",
      "Find the row for your subdomain → click manage in the CNAME column",
      "Enter sites.woco-net.com. ← trailing dot required",
      "Tick the confirmation checkbox",
      "Click Accept settings",
    ],
    aRecordSteps: [
      "Log in at strato.de → Domains → Domain management",
      "Click the cogwheel next to your domain → DNS tab",
      "Find the A record row for the root/@ → click manage",
      "Enter 46.225.174.72",
      "Tick the confirmation checkbox → Click Accept settings",
    ],
    gotcha: "Trailing dot required on CNAME targets. Enabling a CNAME removes all Strato-managed services (email, FTP) for that subdomain.",
  },
  Fasthosts: {
    provider: "Fasthosts",
    apexSupported: true,
    cnameSteps: [
      "Log in to Fasthosts account → Domain Names in left menu",
      "Click the DNS icon next to your domain",
      "Scroll to CNAME Records → Add CNAME Record",
      "Host Name: subdomain (e.g. www) | Points To: sites.woco-net.com",
      "Click Save",
    ],
    aRecordSteps: [
      "Log in to Fasthosts account → Domain Names in left menu",
      "Click the DNS icon next to your domain",
      "Scroll to A Records → Add A Record",
      "Host Name: @ | Points To: 46.225.174.72",
      "Click Save",
    ],
    gotcha: "Fasthosts UI has been redesigned multiple times — the DNS section may be under 'Advanced DNS' in older accounts.",
  },
  "Network Solutions": {
    provider: "Network Solutions",
    apexSupported: true,
    cnameSteps: [
      "Log in → My Account → Domains → your domain",
      "Scroll to Advanced Tools → Manage next to Advanced DNS Records",
      "Add Record → Type: CNAME (Alias) | Refers to: Other Host",
      "Alias: subdomain (e.g. www) | Host Name: sites.woco-net.com",
      "Click Continue → Save Changes",
    ],
    aRecordSteps: [
      "Log in → My Account → Domains → your domain",
      "Scroll to Advanced Tools → Manage next to Advanced DNS Records",
      "Add Record → Type: A (Address) | Refers to: Other Host",
      "Host Name: @ | IP Address: 46.225.174.72",
      "Click Continue → Save Changes",
    ],
    gotcha: "Network Solutions calls CNAME records 'Alias' — the Refers to field must be set to Other Host for an external target.",
  },
  DreamHost: {
    provider: "DreamHost",
    apexSupported: true,
    cnameSteps: [
      "Log in to panel.dreamhost.com → Domains → Manage Domains",
      "Click DNS below your domain → Add Record",
      "Hover over CNAME Record section → click ADD",
      "Host: subdomain (e.g. www) | Points to: sites.woco-net.com",
      "Click Add Record",
    ],
    aRecordSteps: [
      "Log in to panel.dreamhost.com → Domains → Manage Domains",
      "Click DNS below your domain → Add Record",
      "Hover over A Record section → click ADD",
      "Host: @ | Points to: 46.225.174.72",
      "Click Add Record",
    ],
    gotcha: "'You already have a record for this name' error means a conflicting A or CNAME exists — delete it first.",
  },
  Bluehost: {
    provider: "Bluehost",
    apexSupported: true,
    cnameSteps: [
      "Log in → Hosting → your domain → Manage → DNS tab",
      "Under CNAME section → Add record",
      "Host Record: subdomain (e.g. www) | Type: CNAME | Points To: sites.woco-net.com",
      "Click Add Record",
    ],
    aRecordSteps: [
      "Log in → Hosting → your domain → Manage → DNS tab",
      "Under A (Host) section → Add record",
      "Host Record: @ | Type: A | Points To: 46.225.174.72",
      "Click Add Record",
    ],
    gotcha: "Bluehost has two DNS paths — the simplified Domains panel and full cPanel Zone Editor. Either works.",
  },
  HostGator: {
    provider: "HostGator",
    apexSupported: true,
    cnameSteps: [
      "Log in to cPanel (yourdomain.com/cpanel) → Domains → Zone Editor",
      "Manage next to your domain → Add Record",
      "Type: CNAME | Name: subdomain.yourdomain.com | Record: sites.woco-net.com",
      "Click Add Record",
    ],
    aRecordSteps: [
      "Log in to cPanel (yourdomain.com/cpanel) → Domains → Zone Editor",
      "Manage next to your domain → Add Record",
      "Type: A | Name: yourdomain.com. | Record: 46.225.174.72",
      "Click Add Record",
    ],
  },
  "Heart Internet": {
    provider: "Heart Internet",
    apexSupported: true,
    cnameSteps: [
      "Log in to Heart Internet Control Panel",
      "Domain names (right-hand menu under Manage) → select domain → Manage Now",
      "Click DNS Management",
      "Under Create New A/AAAA/CNAME Records:",
      "Subdomain: your subdomain (e.g. www) | Address: sites.woco-net.com. ← trailing dot required",
      "Click Update DNS",
    ],
    aRecordSteps: [
      "Log in to Heart Internet Control Panel",
      "Domain names → select domain → Manage Now",
      "Click DNS Management → find the A record for the root/@ → edit",
      "Set Address to 46.225.174.72",
      "Click Update DNS",
    ],
    gotcha: "Trailing dot is required on the CNAME target.",
  },
  "Hetzner DNS": {
    provider: "Hetzner DNS",
    apexSupported: true,
    cnameSteps: [
      "Log in to console.hetzner.com → DNS → click your zone",
      "Click Records tab → Type: CNAME",
      "Name: subdomain (e.g. www) | Value: sites.woco-net.com. ← trailing dot required",
      "Set TTL → click Add record",
    ],
    aRecordSteps: [
      "Log in to console.hetzner.com → DNS → click your zone",
      "Click Records tab → Type: A",
      "Name: @ | Value: 46.225.174.72",
      "Set TTL → click Add record",
    ],
    gotcha: "Trailing dot is mandatory on CNAME targets — without it, Hetzner appends the current zone name.",
  },
};

const GENERIC: ProviderInstructions = {
  provider: "Unknown",
  apexSupported: true,
  cnameSteps: [
    "Log in to your DNS provider's control panel",
    "Find the DNS records section for your domain",
    "Add a new CNAME record:",
    "  Type: CNAME (sometimes called 'Alias')",
    "  Name / Host: your subdomain (e.g. www — not the full domain)",
    "  Target / Value / Points to: sites.woco-net.com",
    "Save the record",
  ],
  aRecordSteps: [
    "Log in to your DNS provider's control panel",
    "Find the DNS records section for your domain",
    "Add or edit the A record for the root/apex domain:",
    "  Type: A",
    "  Name / Host: @ (or leave blank)",
    "  Value / IP: 46.225.174.72",
    "Save the record",
  ],
};

export function getProviderInstructions(provider: string): ProviderInstructions {
  return INSTRUCTIONS[provider] ?? GENERIC;
}
